### ISSUE TITLE
Errors in last update from few minutes ago.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#147]
Updated, restarted kodi like the changelog did say.
Wiped all caches within Fen, as soon as I hit something (movie as a example) immediately I get a error before scraping starts (does not scrape,) 

Here is the log (from phone, so little mess) 

2020-02-27 18:29:28.975 T:30706   ERROR: GetDirectory - Error getting plugin://plugin.video.fen/?foldername=Clean%20Settings%20Files&iconImage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fscript.tiki.artwork%2fresources%2fmedia%2flight%2fsettings2.png&list_name=Clean%20Settings%20Files&mode=clean_settings
2020-02-27 18:29:28.977 T:30224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=Clean%20Settings%20Files&iconImage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fscript.tiki.artwork%2fresources%2fmedia%2flight%2fsettings2.png&list_name=Clean%20Settings%20Files&mode=clean_settings) failed
2020-02-27 18:29:37.510 T:30719   ERROR: GetDirectory - Error getting plugin://plugin.video.fen/?foldername=Clear%20All%20Cache&iconImage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fscript.tiki.artwork%2fresources%2fmedia%2flight%2fsettings2.png&list_name=Tools%20Clear%20All%20Cache&mode=clear_all_cache
2020-02-27 18:29:37.512 T:30224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=Clear%20All%20Cache&iconImage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fscript.tiki.artwork%2fresources%2fmedia%2flight%2fsettings2.png&list_name=Tools%20Clear%20All%20Cache&mode=clear_all_cache) failed
2020-02-27 18:29:45.979 T:30821   ERROR: Exception in thread Thread-9:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/indexers/movies.py", line 256, in set_info
                                                playcount, overlay = get_watched_status(self.watched_info, self.use_trakt, 'movie', meta['tmdb_id'])
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
2020-02-27 18:29:50.577 T:30883   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'meta' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 87, in <module>
                                                literal_eval(params.get('library', 'False')), params.get('background'), literal_eval(params.get('autoplay', 'None')))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 66, in playback_prep
                                                self.search_info = self._search_info()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 465, in _search_info
                                                else: search_title = meta['title']
                                            NameError: global name 'meta' is not defined
                                            -->End of Python script error report<--
2020-02-27 18:29:52.681 T:30224  NOTICE: CWinSystemAndroid::DestroyWindow
2020-02-27 18:29:52.705 T:30193 WARNING: CPeripheralBusAndroid: failed to update input device with ID 5 because it couldn't be found

**Comment by Tinuz97** [comment]
*Oneplus 5 phone, Android 9.

**Comment by Tinuz97** [comment]
Removed the tiki meta and Fen in user data, setup Fen again, now it is working.
But I think this will give issues for other users (never had to do this with Fen).

**Comment by Tinuz97** [comment]
Closed kodi (after working like one message above), start kodi, and error back again.

New log 

Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/indexers/movies.py", line 256, in set_info
                                                playcount, overlay = get_watched_status(self.watched_info, self.use_trakt, 'movie', meta['tmdb_id'])
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
2020-02-27 19:05:50.916 T:13394  NOTICE: ###trouble with set###: no such table: metadata
2020-02-27 19:05:56.081 T:13470  NOTICE: Previous line repeats 10 times.
2020-02-27 19:05:56.081 T:13470   ERROR: GetDirectory - Error getting /
2020-02-27 19:05:59.614 T:12856   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/AGC Studios.png
2020-02-27 19:06:00.066 T:13490   ERROR: GetDirectory - Error getting /
2020-02-27 19:06:00.363 T:12856   ERROR: Previous line repeats 1 times.
2020-02-27 19:06:00.363 T:12856   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/
2020-02-27 19:06:04.679 T:13631   ERROR: GetDirectory - Error getting /
2020-02-27 19:06:08.037 T:13651   ERROR: Previous line repeats 1 times.
2020-02-27 19:06:08.037 T:13651   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'meta' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 87, in <module>
                                                literal_eval(params.get('library', 'False')), params.get('background'), literal_eval(params.get('autoplay', 'None')))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 66, in playback_prep
                                                self.search_info = self._search_info()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 465, in _search_info
                                                else: search_title = meta['title']
                                            NameError: global name 'meta' is not defined
                                            -->End of Python script error report<--
2020-02-27 19:06:11.955 T:12821  NOTICE: CWinSystemAndroid::DestroyWindow
2020-02-27 19:06:11.969 T:12791 WARNING: CPeripheralBusAndroid: failed to update input device with ID 3 because it couldn't be found
2020-02-27 19:06:11.970 T:12791 WARNING: CPeripheralBusAndroid: failed to update input device with ID 5 because it couldn't be found

**Comment by Tikipeter** [comment]
Yeah, I knew this update would be a disaster. Hopefully this problem's fixed with v.1.6.03a

**Comment by Tinuz97** [comment]
A did fix it (scraped a movie, closed kodi, scraped a movie again to be sure, works great now) 👍
