### ISSUE TITLE
Widget disapearing - not showing

### ISSUE THREAD

**Issue by freaktabnl** [Tikipeter/repository.tikipeter#176]
Widgets are disapearing and Fenstuary giving this error:

2023-03-06 09:40:02.326 T:32148   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\RGF\Desktop\KODI 20\Kodi\portable_data\addons\script.fenstruary.helper\resources\lib\default.py", line 3, in <module>
                                                       routing()
                                                     File "C:\Users\RGF\Desktop\KODI 20\Kodi\portable_data\addons\script.fenstruary.helper\resources\lib\modules\router.py", line 25, in routing
                                                       return CPaths(_get('cpath_setting')).manage_main_menu_path()
                                                     File "C:\Users\RGF\Desktop\KODI 20\Kodi\portable_data\addons\script.fenstruary.helper\resources\lib\modules\cpath_maker.py", line 121, in manage_main_menu_path
                                                       cpath_path = self.cpath_maker()
                                                     File "C:\Users\RGF\Desktop\KODI 20\Kodi\portable_data\addons\script.fenstruary.helper\resources\lib\modules\cpath_maker.py", line 168, in cpath_maker
                                                       else: return self.cpath_maker(choice[0], choice[1])
                                                     File "C:\Users\RGF\Desktop\KODI 20\Kodi\portable_data\addons\script.fenstruary.helper\resources\lib\modules\cpath_maker.py", line 144, in cpath_maker
                                                       result = files_get_directory(path)
                                                     File "C:\Users\RGF\Desktop\KODI 20\Kodi\portable_data\addons\script.fenstruary.helper\resources\lib\modules\cpath_maker.py", line 194, in files_get_directory
                                                       return result.get('files', None)
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--

**Comment by freaktabnl** [comment]
Still error here

**Comment by freaktabnl** [comment]
Running Kodi 20 (Nexus)

**Comment by Tikipeter** [comment]
Delete the 6 files in the Fenstruary folder starting with `script-fenstruary`. Then reload the skin. Then clear all the widgets. Then restart Kodi and start again.

Note for next time: I DO NOT support this skin. Please do not post any more issues here for addons/skins that don't come from this repository.
