### ISSUE TITLE
Getting error on progress episodes

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/repository.tikipeter#208]
First Thank you for this amazing addon love Fen,,Just noticed after The last update when going into progress episodes I get an error was working prior to this last update appreciate any help or feedback please

**Comment by Tinuz97** [comment]
Me also, wanted to make a ticket, but you already did.

Here is the log @Tikipeter 

2020-05-14 14:04:04.035 T:7592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'json' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module>
                                                routing()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 69, in routing
                                                build_in_progress_episode()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\in_progress.py", line 87, in build_in_progress_episode
                                                meta_user_info_json = json.dumps(meta_user_info)
                                            NameError: global name 'json' is not defined
                                            -->End of Python script error report<--
2020-05-14 14:04:04.085 T:4800   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?foldername=In%20Progress%20Episodes&iconImage=player.png&mode=build_in_progress_episode&name=In%20Progress%20Episodes
2020-05-14 14:04:04.092 T:2368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=In%20Progress%20Episodes&iconImage=player.png&mode=build_in_progress_episode&name=In%20Progress%20Episodes) failed

**Comment by xyzfre** [comment]
After I got the error I cleared all cache Just to see if it helps and afterwords I got a black screen so I had to force stop Kodi first time that happens when I clear all cache In Fen

**Comment by Tikipeter** [comment]
Thank you both. I'll push an update with the fix.

**Comment by xyzfre** [comment]
Thank you and appreciate all the hard work you put into Fen it’s a amazing addon,, One thing I did notice from the last update the scraping is a lot faster now on my end
