### ISSUE TITLE
trakt error with widgets

### ISSUE THREAD

**Issue by SJ50** [Tikipeter/repository.tikipeter#214]
I am getting following error and none of the takt based widgets are working
full log http://paste.kodi.tv/ucohohoyum
````
2020-05-21 21:21:43.045 T:8217   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name build_trakt_list
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 4, in <module>
                                                routing()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/router.py", line 38, in routing

**Comment by Tikipeter** [comment]
Please delete the Trakt widgets and then remake them. That should fix the issue.

**Comment by SJ50** [comment]
so path changed from trakt.build to trakt.list.build right?

**Comment by Tikipeter** [comment]
Essentially. I moved some trakt functions from one module to another.

**Comment by SJ50** [comment]
I just 'sed' and replaced all paths, widgets are working
