### ISSUE TITLE
'Because you Watched' Error.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#224]
LOG:

2020-06-09 00:05:28.665 T:10472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module>
                                                routing()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 14, in routing
                                                else: exec('Navigator().%s()' % mode.split('.')[1])
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\navigator.py", line 590, in because_you_watched
                                                name = because_insert % item[name_index]
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-06-09 00:05:28.724 T:1568   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?foldername=Because%20You%20Watched&iconImage=because_you_watched.png&menu_type=movie&mode=navigator.because_you_watched&name=32474
2020-06-09 00:05:28.727 T:3372   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=Because%20You%20Watched&iconImage=because_you_watched.png&menu_type=movie&mode=navigator.because_you_watched&name=32474) failed

**Comment by Tikipeter** [comment]
I'm going to put a new version of Fen in the strings.po Issue thread that should fix this moving forward. Hopefully.

**Comment by Tinuz97** [comment]
Checked this one,working 100% again. 🥇
