### ISSUE TITLE
Error wiping setting option, and error with the wipe all cache option.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#232]
I noticed this after a clean Fen install.
And i think i know why, there is no fencache database file after a clean install, but a fen_cache2.db file.
Correct me if i am wrong,so it is trying to wipe something that does not exist i guess.

If you try this,make sure you wipe Fen in User Data folder, and let it create a clean one.

LOG:

2020-06-19 15:32:44.177 T:8052   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such table: fencache
                                            Traceback (most recent call last):
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module>
                                                routing()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 350, in routing
                                                clear_all_cache()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\nav_utils.py", line 633, in clear_all_cache
                                                clear_cache(cache_type[0], silent=True)
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\nav_utils.py", line 596, in clear_cache
                                                if not cached_page_clear(silent=silent): return
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\nav_utils.py", line 556, in cached_page_clear
                                                dbcur.execute("SELECT id FROM fencache WHERE id LIKE 'fen_page_cache_%'")
                                            OperationalError: no such table: fencache
                                            -->End of Python script error report<--

**Comment by Tinuz97** [comment]
These are created af a clean install, if you look at the timestamp,it is trying to make a new fen_cache.db (after i hit the cleaning options for settings, and wipe all option), but the fen_cache2.db is created first.

The wipe options (settings and all cache) is trying to wipe fen_cache.db i guess?
But trows error because there is noting in there? (0KB)


![image](https://user-images.githubusercontent.com/47715606/85138444-10a4a500-b243-11ea-8210-2517a82b22b1.png)

**Comment by Tinuz97** [comment]
I could be totally wrong (i am not a programmer,my logic says this lol).
So curious why the error happens.

**Comment by jigoop1** [comment]
@Tinuz97 
for the error for wipe all cache option
in file nav_utils.py
line no 315 
cache_file = os.path.join(profile_dir, "fen_cache.db")
should be  
cache_file = os.path.join(profile_dir, "fen_cache2.db")
and on line 549  
FEN_DB = os.path.join(profile_dir, "fen_cache.db")
should be  
FEN_DB = os.path.join(profile_dir, "fen_cache2.db")
i thinks @Tikipeter  change fen_cache.db to fen_cache2.db

**Comment by Tinuz97** [comment]
Yeah that I how I thought it also, but English not my main language.

But that it what I think it is also.

**Comment by Tikipeter** [comment]
You are both correct. Good job guys. 👍 👍 

Fix in next update.

**Comment by Tinuz97** [comment]
Fix working, thx.
