### ISSUE TITLE
errr when the user try to use the cerificate filter at discover function

### ISSUE THREAD

**Issue by chrisnikol** [Tikipeter/repository.tikipeter#241]
When the user is trying to use the certificate filter at discover the fen show an error message.

I am using kodi 18.7 64 bit fen version 1.7.07 at windows 10 pro 64 bit 1909

At the log file exist this lines:

2020-07-16 09:40:06.321 T:14700 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2020-07-16 09:40:14.366 T:960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'function' object is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module>
                                                routing()
                                              File "C:\Users\....\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 22, in routing
                                                exec(action_object)
                                              File "discover_string", line 1, in <module>
                                              File "C:\Users\.....\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\discover.py", line 276, in certification
                                                certifications_list = [i.upper() for i in certifications]
                                            TypeError: 'function' object is not iterable
                                            -->End of Python script error report<-- 

Please notice that this is the normal level log file and not the debug level

As always thank you for this amazing addon.

**Comment by Tikipeter** [comment]
Thanks @chrisnikol 

Fixed for next update.
