### ISSUE TITLE
Wanted to start clean,errors.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#257]
Normally if i tested Fen versions,i always start clean by wiping the plugin.video.fen folder in user data,that always works.

But now if i do that i get this after wiping the folder in user data,it does not create a new one (like before)
Instant error after trying to launch Fen.
Why does it not create a new folder like before? It is missing the files (says the log),because it does not create a new folder.

2020-09-01 17:52:19.891 T:10824   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-09-01 17:52:20.232 T:3456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No such file or directory: 'C:\\Users\\Tinuz\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.fen\\settings.xml'
                                            Traceback (most recent call last):
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 5, in <module>
                                                routing(argv[2])
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 11, in routing
                                                exec('Navigator(params).%s()' % mode.split('.')[1])
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\navigator.py", line 28, in __init__
                                                self.icon_directory = settings.get_theme()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\settings.py", line 19, in get_theme
                                                theme = 'light' if get_setting('fen.theme') in ('0', '-', '') else 'heavy'
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\setting_reader.py", line 10, in get_setting
                                                except: settings_dict = make_settings_dict()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\setting_reader.py", line 28, in make_settings_dict
                                                root = ET.parse(settings_xml).getroot()
                                              File "C:\Program Files\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1182, in parse
                                                tree.parse(source, parser)
                                              File "C:\Program Files\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 647, in parse
                                                source = open(source, "rb")
                                            IOError: [Errno 2] No such file or directory: 'C:\\Users\\Tinuz\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.fen\\settings.xml'
                                            -->End of Python script error report<--
2020-09-01 17:52:20.288 T:9784   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?content_type=video
2020-09-01 17:52:20.302 T:10824   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?content_type=video) failed

**Comment by Tinuz97** [comment]
Oh,windows 10, Fen version 1.8.0.1

**Comment by Tikipeter** [comment]
Let me look into it...

**Comment by Tikipeter** [comment]
Damn, I'll have to write a function to remake default user settings file because of the new settings handler.
Give me a bit of time Tinuz.

**Comment by Tinuz97** [comment]
No problem.
Maybey that other guy issue is related to the one I have? (that other issue here on github).

**Comment by Tikipeter** [comment]
Possibly, but I have a feeling it might be something to do with a Wizard. Those things are cancer to Kodi, and should never be installed.

**Comment by Tinuz97** [comment]
So if you remove plugin.video.fen folder in User Data (on Windows, kodi not open), start kodi, it creates a new one?

**Comment by Tikipeter** [comment]
It kind of did because I would check for the Fen databases which were in there and create a folder if it didn't exist.

Kodi I know does create a new settings file with default settings if it is deleted, but it looks like only upon a call to get a setting, which Fen no longer does through Kodi's builtin module. That's likely why it's not triggering a remake.

And since Fen will check for a setting (and fail) before it checks for the existence of `plugin.video.fen`, then it isn't getting created at all.

I need to mimic what Kodi does, and make a new `settings.xml` file with default settings if it doesn't exist.

**Comment by Tikipeter** [comment]
I'm hoping v.1.8.05 which I'll upload soon will fix this issue.
I hopefully found an easier route than remaking a default settings.xml file.

**Comment by Tinuz97** [comment]
Yes, v.1.8.05 did fix it.
Error on first launch (probably did need to make the xml?), 2nd launch it did work :)
