### ISSUE TITLE
Error on opening some TV shows. (not all) 

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#264]
I get errors on opening some TV shows, they won't open, and drop a error immediately.

This is The Boys TV show for a example.

Fen 1.8.0.7B (previous version did this also) 
Any idea @Tikipeter?

Used all wiping and cleaning options in Fen, rebooted kodi etc.

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 5, in <module>
                                                routing(argv[2])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/router.py", line 83, in routing
                                                build_season_list(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/indexers/tvshows.py", line 344, in build_season_list
                                                season_data = tikimeta.all_episodes_meta(meta['tmdb_id'], meta['tvdb_id'], meta['tvdb_summary']['airedSeasons'], meta['season_data'], meta_user_info)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tikimeta/lib/tikimeta/__init__.py", line 22, in all_episodes_meta
                                                return getAllEpisodes(media_id, tvdb_id, seasons, tmdb_data, user_info, hours)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tikimeta/lib/tikimeta/build_meta.py", line 207, in getAllEpisodes
                                                return _return_meta(data, use_tmdb)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tikimeta/lib/tikimeta/build_meta.py", line 181, in _return_meta
                                                meta = buildSeasonsMeta(data, seasons, tmdb_data, image_resolution, use_tmdb=use_tmdb)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.tikimeta/lib/tikimeta/build_meta.py", line 480, in buildSeasonsMeta
                                                episodes = [d for d in data if d['airedSeason'] == i]
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
2020-09-14 01:00:47.451 T:12945   ERROR: GetDirectory - Error getting plugin://plugin.video.fen/?meta=%7b%22rating%22%3a%208.4000000000000004%2c%20%22alternative_titles%22%3a%20%5b%5d%2c%20%22total_episodes%22%3a%2016%2c%20%22fanart_added%22%3a%20true%2c%20%22year%22%3a%202019%2c%20%22duration%22%3a%203600%2c%20%22overlay%22%3a%204%2c%20%22landscape%22%3a%20%22https%3a%2f%2fassets.fanart.tv%2ffanart%2ftv%2f355567%2ftvthumb%2fthe-boys-5d42fbeed1d0f.jpg%22%2c%20%22extra_info%22%3a%20%7b%22status%22%3a%20%22Returning%20Series%22%2c%20%22next_episode_to_air%22%3a%20%22%5b2020-09-18%5d%20S02E05%20-%20Aflevering%205%22%2c%20%22created_by%22%3a%20%22Eric%20Kripke%22%2c%20%22homepage%22%3a%20%22https%3a%2f%2fwww.amazon.com%2fdp%2fB07QQQHK1Y%22%2c%20%22last_episode_to_air%22%3a%20%22%5b2020-09-11%5d%20S02E04%20-%20Aflevering%204%22%2c%20%22type%22%3a%20%22Scripted%22%7d%2c%20%22total_watched%22%3a%20%228%22%2c%20%22plot%22%3a%20%22In%20een%20wereld%20waar%20superhelden%20de%20duistere%20kant%20van%20hun%20overweldigende%20beroemdheid%20en%20roem%20omhelzen%2c%20vormt%20zich%20een%20groep%20burgerwachten%20die%20informeel%20bekend%20staan%20als%20%27The%20Boys%27.%20Hun%20missie%20is%20om%20de%20corrupte%20superhelden%20aan%20te%20pakken%20met%20niet%20meer%20dan%20een%20stel%20harde%20vuisten%20en%20de%20wil%20om%20te%20vechten%20tot%20hun%20beschikking.%20Het%20zijn%20de%20machteloze%20tegen%20de%20super%20krachtige%20als%20The%20Boys%20beginnen%20aan%20een%20hero%5cu00efsche%20zoektocht%20om%20de%20waarheid%20over%20%27The%20Seven%27%20en%20hun%20formidabele%20Vought-steun%20bloot%20te%20leggen.%22%2c%20%22votes%22%3a%201753%2c%20%22title%22%3a%20%22The%20Boys%22%2c%20%22fanart%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw1280%2fmGVrXeIjyecj6TKmwPVpHlscEmw.jpg%22%2c%20%22mpaa%22%3a%20%22TV-MA%22%2c%20%22writer%22%3a%20%22%22%2c%20%22rootname%22%3a%20%22The%20Boys%20(2019)%22%2c%20%22tmdb_id%22%3a%2076479%2c%20%22poster%22%3a%20%22

**Comment by Tikipeter** [comment]
The error says there's no data for the episodes info.
I don't know why this would be if you have cleared all the caches. It could happen if there was a glitch with TVDb, but that would have been cleared.

As a test, refresh the meta for just this one show (The Boys) by bringing up context menu, selecting "Add/Remove" and then "Remove Cache (Re-cache item)" or something like that. See if it works after that.

**Comment by Tinuz97** [comment]
That did the trick, working now (the boys), thx.

**Comment by Tikipeter** [comment]
Great. I'll leave rhis open for a bit in case there's other issues. Also, I'll check the normal cache clearing method in case something's wrong with it as well.
