### ISSUE TITLE
Context menu Options > Clear Scrapers Cache gives error "cannot import name 'clear_cache' from 'caches'"

### ISSUE THREAD

**Issue by meesterexx** [Tikipeter/repository.tikipeter#317]
Fen 3.2.04, Kodi 20.2 x64, Windows 11, 3 different builds (AH2, Fentastic, Custom skin mod) all give the following error in log when using context menu item Options > Clear Scrapers Cache (both from widget and inside addon):

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ImportError'>
Error Contents: cannot import name 'clear_cache' from 'caches' (C:\Ktest20\portable_data\addons\plugin.video.fen\resources\lib\caches\__init__.py)
Traceback (most recent call last):
  File "C:\Ktest20\portable_data\addons\plugin.video.fen\resources\lib\fen.py", line 6, in <module>
    routing(sys)
  File "C:\Ktest20\portable_data\addons\plugin.video.fen\resources\lib\modules\router.py", line 51, in routing
    return exec('dialogs.%s(params)' % mode)
  File "<string>", line 1, in <module>
  File "C:\Ktest20\portable_data\addons\plugin.video.fen\resources\lib\indexers\dialogs.py", line 898, in options_menu_choice
    return clear_scrapers_cache()
  File "C:\Ktest20\portable_data\addons\plugin.video.fen\resources\lib\modules\source_utils.py", line 132, in clear_scrapers_cache
    from caches import clear_cache
ImportError: cannot import name 'clear_cache' from 'caches' (C:\Ktest20\portable_data\addons\plugin.video.fen\resources\lib\caches\__init__.py)
```

Clearing cache from the Tools > Clear Databases menu works as expected.
Please let me know if you need anything else from me. Thank you!

**Comment by Tikipeter** [comment]
Thank you.

Fixed for next update.
