### ISSUE TITLE
Error(s) , see log.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#32]
I get errors some times after scraping, if Fen is done with searching sources, and it wants to create the links, i get a error pop-up (not al the time, but let's say after 2-5 movies.), and it goes back to my movie overview ( so not creating the links page)
This issue started after the last update (never had it before)

Here is the log:

2019-09-25 02:19:28.996 T:2812   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Tinuz\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.fen\Movies Downloads\
2019-09-25 02:19:50.671 T:7372  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
2019-09-25 02:19:51.206 T:7228   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Tinuz\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.fen\Movies Downloads\
2019-09-25 02:20:12.420 T:1696  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
2019-09-25 02:20:13.011 T:2548   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Tinuz\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.fen\Movies Downloads\
2019-09-25 02:20:34.856 T:6960  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
2019-09-25 02:20:35.432 T:8148   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Tinuz\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.fen\Movies Downloads\
2019-09-25 02:20:56.185 T:1264  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
2019-09-25 02:20:56.734 T:10884   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Tinuz\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.fen\Movies Downloads\
2019-09-25 02:21:10.832 T:1264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'label'
                                            Traceback (most recent call last):
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\fen.py", line 87, in <module>
                                                params.get('plot'), params.get('meta'), literal_eval(params.get('library', 'False')), params.get('background'))
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 58, in playback_prep
                                                self.get_sources()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 76, in get_sources
                                                results = self.number_results(results)
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 143, in number_results
                                                i['label'] = '%02d | %s' % (n, i['label'])
                                            KeyError: 'label'
                                            -->End of Python script error report<--

**Comment by Tinuz97** [comment]
PS:
I also used clear all cache options, i even removed the user data folder for Fen, but issue still there.

**Comment by Tinuz97** [comment]
Something in sources.py i guess that is causing the errors ?

**Comment by Tikipeter** [comment]
Thanks Tinuz97.
Indeed, some bad code in sources.py. Must have miss typed last update. Fixed for next update. :)

**Comment by Tikipeter** [comment]
Should be fixed with v.1.5.52.

**Comment by Tinuz97** [comment]
Thx, going to test in a few hours (bed time in the netherlands), thx for the fix/update.
