### ISSUE TITLE
Issue authorizing AllDebrid

### ISSUE THREAD

**Issue by gabrielstedman** [Tikipeter/repository.tikipeter#328]
After introducing PIN for AllDebrid I get:

```python3
2023-09-17 15:55:42.242 T:15792   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'user'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kiosk\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 6, in <module>
                                                       routing(sys)
                                                     File "C:\Users\kiosk\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 49, in routing
                                                       return exec('dialogs.%s(params)' % mode)
                                                     File "<string>", line 1, in <module>
                                                     File "C:\Users\kiosk\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\dialogs.py", line 84, in auth_accounts_choice
                                                       else: AllDebridAPI().auth()
                                                     File "C:\Users\kiosk\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\apis\alldebrid_api.py", line 66, in auth
                                                       set_setting('ad.account_id', str(account_info['user']['username']))
                                                   KeyError: 'user'
                                                   -->End of Python script error report<--
                                                   

```

**Comment by Tikipeter** [comment]
Paid account active?

**Comment by Tikipeter** [comment]
All Debrid looks to be having several issues at the moment.

**Comment by gabrielstedman** [comment]
Yes it does look to he on Alldebrid side as I get similar outcome with other apps.

I'll leave this here,you might wish to handle the exception gracefully and show a message to the user .
