### ISSUE TITLE
TV Shows section got broken.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#49]
TV Show section got broken in the latest Fen version 1.5.64a
If i open it, no problem,if i want to open a TV Show, let's say Watchmen,i get this error.

LOG:

2019-11-04 16:36:58.701 T:1416   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?foldername=Clear%20All%20Cache&iconImage=C%3a%5cUsers%5cTinuz%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings2.png&info=Clear%20Fen%20Meta%2c%20Lists%2c%20Navigated%20Pages%2c%20Providers%20(Internal%2fExternal)%2c%20Trakt%2c%20RD%20and%20PM%20Clouds%20Cache.%20This%20cannot%20be%20undone.&list_name=Tools%20Clear%20All%20Cache&mode=clear_all_cache
2019-11-04 16:36:58.709 T:6180   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=Clear%20All%20Cache&iconImage=C%3a%5cUsers%5cTinuz%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings2.png&info=Clear%20Fen%20Meta%2c%20Lists%2c%20Navigated%20Pages%2c%20Providers%20(Internal%2fExternal)%2c%20Trakt%2c%20RD%20and%20PM%20Clouds%20Cache.%20This%20cannot%20be%20undone.&list_name=Tools%20Clear%20All%20Cache&mode=clear_all_cache) failed
2019-11-04 16:37:13.888 T:4412   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\fen.py", line 60, in <module>
                                                build_season_list()
                                              File "C:\Users\Tinuz\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\tvshows.py", line 372, in build_season_list
                                                meta = json.loads(window.getProperty('fen_media_meta'))
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2019-11-04 16:37:13.927 T:3292   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?meta=%7b%22rating%22%3a%207.5%2c%20%22total_episodes%22%3a%209%2c%20%22gif_poster%22%3a%20%22%22%2c%20%22fanart_added%22%3a%20false%2c%20%22year%22%3a%202019%2c%20%22duration%22%3a%203600%2c%20%22landscape%22%3a%20%22%22%2c%20%22total_watched%22%3a%20%220%22%2c%20%22plot%22%3a%20%22Set%20in%20an%20alternate%20history%20where%20%5cu201csuperheroes%5cu201d%20are%20treated%20as%20outlaws%2c%20%5cu201cWatchmen%5cu201d%20embraces%20the%20nostalgia%20of%20the%20original%20groundbreaking%20graphic%20novel%20while%20attempting%20to%20break%20new%20ground%20of%20its%20own.%22%2c%20%22votes%22%3a%2046%2c%20%22title%22%3a%20%22Watchmen%22%2c%20%22fanart%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fgFeaXBnOO14aOQhMQrr5tbyhMTw.jpg%22%2c%20%22mpaa%22%3a%20%22TV-MA%22%2c%20%22writer%22%3a%20%22%22%2c%20%22rootname%22%3a%20%22Watchmen%20(2019)%22%2c%20%22clearart%22%3a%20%22%22%2c%20%22tmdb_id%22%3a%2079788%2c%20%22poster%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fm8rWq3j73ZGhDuSCZWMMoE9ePH1.jpg%22%2c%20%22tvshowtitle%22%3a%20%22Watchmen%22%2c%20%22tvdb_id%22%3a%20360733%2c%20%22total_seasons%22%3a%201%2c%20%22mediatype%22%3a%20%22tvshow%22%2c%20%22imdb_id%22%3a%20%22tt7049682%22%2c%20%22director%22%3a%20%22%22%2c%20%22imdbnumber%22%3a%20%22tt7049682%22%2c%20%22studio%22%3a%20%5b%22HBO%22%5d%2c%20%22genre%22%3a%20%22Crime%2c%20Drama%2c%20Action%20%26%20Adventure%2c%20Sci-Fi%20%26%20Fantasy%22%2c%20%22season_data%22%3a%20%5b%7b%22poster_path%22%3a%20%22%2fm8rWq3j73ZGhDuSCZWMMoE9ePH1.jpg%22%2c%20%22name%22%3a%20%22Season%201%22%2c%20%22air_date%22%3a%20%222019-10-20%22%2c%20%22overview%22%3a%20%22%22%2c%20%22episode_count%22%3a%209%2c%20%22season_number%22%3a%201%2c%20%22id%22%3a%20104229%7d%5d%2c%20%22banner%22%3a%20%22C%3a%5c%5cUsers%5c%5cTinuz%5c%5cAppData%5c%5cRoaming%5c%5cKodi%5c%5caddons%5c%5cscript.module.tikimeta%5c%5cresources%5c%5cdefault_images%5c%5ctikimeta_blank_banner.png%22%2c%20%22kyradb_added%22%3a%20false%2c%20%22all_trailers%22%3a%20%5b%7b%22name%22%3a%20%22Watchmen%20%7c%20Official%20Tease%20%7c%20HBO%22%2c%20%22iso_3166_1%22%3a%20%22US%22%2c%20%22site%22%3a%20%22YouTube%22%2c%20%22iso_639_1%22%3a%20%22en%22%2c%20%22key%22%3a%20%22zymgtV99Rko%22%2c%20%22type%22%3a%20%22Teaser%22%2c%20%22id%22%3a%20%225cd317b60e0a264a95029824%22%2c%20%22size%22%3a%201080%7d%2c%20%7b%22name%22%3a%20%22Watchmen%3a%20Official%20Trailer%20%7c%20HBO%22%2c%20%22iso_3166_1%22%3a%20%22US%22%2c%20%22site%22%3a%20%22YouTube%22%2c%20%22iso_639_1%22%3a%20%22en%22%2c%20%22key%22%3a%20%22-33JCGEGzwU%22%2c%20%22type%22%3a%20%22Trailer%22%2c%20%22id%22%3a%20%225d8d4ee55b370d00198c7aa0%22%2c%20%22size%22%3a%201080%7d%5d%2c%20%22item_no%22%3a%201%2c%20%22total_unwatched%22%3a%20%229%22%2c%20%22discart%22%3a%20%22%22%2c%20%22overlay%22%3a%204%2c%20%22premiered%22%3a%20%222019-10-20%22%2c%20%22clearlogo%22%3a%20%22%22%2c%20%22cast%22%3a%20%5b%7b%22role%22%3a%20%22Angela%20Abar%22%2c%20%22name%22%3a%20%22Regina%20King%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqLPsh6SLw0DSi526g8abEqGJbo3.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Adrian%20Veidt%20%2f%20Ozymandias%22%2c%20%22name%22%3a%20%22Jeremy%20Irons%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f9AWphjIgGX7JjTrwrx3tsTZlUgv.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Judd%20Crawford%22%2c%20%22name%22%3a%20%22Don%20Johnson%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fyQHW10SE2HyuaZmHvUrSxKhqqWg.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Judd%20Crawford%20%2f%20Looking%20Glass%22%2c%20%22name%22%3a%20%22Tim%20Blake%20Nelson%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fdcfdSmVmklb1HXHbB9kySdrl9Nq.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Old%20Man%22%2c%20%22name%22%3a%20%22Louis%20Gossett%20Jr.%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fjZcdOvP9nmLiF7ReKnw4DQbIEid.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Red%20Scare%22%2c%20%22name%22%3a%20%22Andrew%20Howard%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqXEWZDXQRX7UsGlJzKO9dLoCLhq.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Cal%20Abar%22%2c%20%22name%22%3a%20%22Yahya%20Abdul-Mateen%20II%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2flhKObAfoVDU6as0FCgm6y2AAeCO.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Pirate%20Jenny%22%2c%20%22name%22%3a%20%22Adelaide%20Clemens%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fmgOHGacftimR5qBXVzaQoMyVoTX.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Manson%20%2f%20Marionette%22%2c%20%22name%22%3a%20%22Sara%20Vickers%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f4p4OAdzxZ7jyo2lwMEoXu6Fk1zx.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Panda%22%2c%20%22name%22%3a%20%22Jacob%20Ming-Trent%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fxTupOoBtrmhlQQa1vNoS3Di8xT5.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Marcos%20Maez%22%2c%20%22name%22%3a%20%22Tom%20Mison%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2faBDtRCCGgE3Zug2krAhL2IfyvWO.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Topher%20Abar%22%2c%20%22name%22%3a%20%22Dylan%20Schombing%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqDSj1htHETBVvof5Jfg4FRMNnyb.jpg%22%7d%5d%2c%20%22tagline%22%3a%20%22%22%2c%20%22tvdb_summary%22%3a%20%7b%22dvdSeasons%22%3a%20%5b%221%22%5d%2c%20%22dvdEpisodes%22%3a%20%229%22%2c%20%22airedEpisodes%22%3a%20%229%22%2c%20%22airedSeasons%22%3a%20%5b%221%22%5d%7d%2c%20%22playcount%22%3a%200%2c%20%22trailer%22%3a%20%22plugin%3a%2f%2fplugin.video.youtube%2fplay%2f%3fvideo_id%3dzymgtV99Rko%22%7d&mode=build_season_list&tmdb_id=79788
2019-11-04 16:37:13.943 T:6180   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?meta=%7b%22rating%22%3a%207.5%2c%20%22total_episodes%22%3a%209%2c%20%22gif_poster%22%3a%20%22%22%2c%20%22fanart_added%22%3a%20false%2c%20%22year%22%3a%202019%2c%20%22duration%22%3a%203600%2c%20%22landscape%22%3a%20%22%22%2c%20%22total_watched%22%3a%20%220%22%2c%20%22plot%22%3a%20%22Set%20in%20an%20alternate%20history%20where%20%5cu201csuperheroes%5cu201d%20are%20treated%20as%20outlaws%2c%20%5cu201cWatchmen%5cu201d%20embraces%20the%20nostalgia%20of%20the%20original%20groundbreaking%20graphic%20novel%20while%20attempting%20to%20break%20new%20ground%20of%20its%20own.%22%2c%20%22votes%22%3a%2046%2c%20%22title%22%3a%20%22Watchmen%22%2c%20%22fanart%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fgFeaXBnOO14aOQhMQrr5tbyhMTw.jpg%22%2c%20%22mpaa%22%3a%20%22TV-MA%22%2c%20%22writer%22%3a%20%22%22%2c%20%22rootname%22%3a%20%22Watchmen%20(2019)%22%2c%20%22clearart%22%3a%20%22%22%2c%20%22tmdb_id%22%3a%2079788%2c%20%22poster%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fm8rWq3j73ZGhDuSCZWMMoE9ePH1.jpg%22%2c%20%22tvshowtitle%22%3a%20%22Watchmen%22%2c%20%22tvdb_id%22%3a%20360733%2c%20%22total_seasons%22%3a%201%2c%20%22mediatype%22%3a%20%22tvshow%22%2c%20%22imdb_id%22%3a%20%22tt7049682%22%2c%20%22director%22%3a%20%22%22%2c%20%22imdbnumber%22%3a%20%22tt7049682%22%2c%20%22studio%22%3a%20%5b%22HBO%22%5d%2c%20%22genre%22%3a%20%22Crime%2c%20Drama%2c%20Action%20%26%20Adventure%2c%20Sci-Fi%20%26%20Fantasy%22%2c%20%22season_data%22%3a%20%5b%7b%22poster_path%22%3a%20%22%2fm8rWq3j73ZGhDuSCZWMMoE9ePH1.jpg%22%2c%20%22name%22%3a%20%22Season%201%22%2c%20%22air_date%22%3a%20%222019-10-20%22%2c%20%22overview%22%3a%20%22%22%2c%20%22episode_count%22%3a%209%2c%20%22season_number%22%3a%201%2c%20%22id%22%3a%20104229%7d%5d%2c%20%22banner%22%3a%20%22C%3a%5c%5cUsers%5c%5cTinuz%5c%5cAppData%5c%5cRoaming%5c%5cKodi%5c%5caddons%5c%5cscript.module.tikimeta%5c%5cresources%5c%5cdefault_images%5c%5ctikimeta_blank_banner.png%22%2c%20%22kyradb_added%22%3a%20false%2c%20%22all_trailers%22%3a%20%5b%7b%22name%22%3a%20%22Watchmen%20%7c%20Official%20Tease%20%7c%20HBO%22%2c%20%22iso_3166_1%22%3a%20%22US%22%2c%20%22site%22%3a%20%22YouTube%22%2c%20%22iso_639_1%22%3a%20%22en%22%2c%20%22key%22%3a%20%22zymgtV99Rko%22%2c%20%22type%22%3a%20%22Teaser%22%2c%20%22id%22%3a%20%225cd317b60e0a264a95029824%22%2c%20%22size%22%3a%201080%7d%2c%20%7b%22name%22%3a%20%22Watchmen%3a%20Official%20Trailer%20%7c%20HBO%22%2c%20%22iso_3166_1%22%3a%20%22US%22%2c%20%22site%22%3a%20%22YouTube%22%2c%20%22iso_639_1%22%3a%20%22en%22%2c%20%22key%22%3a%20%22-33JCGEGzwU%22%2c%20%22type%22%3a%20%22Trailer%22%2c%20%22id%22%3a%20%225d8d4ee55b370d00198c7aa0%22%2c%20%22size%22%3a%201080%7d%5d%2c%20%22item_no%22%3a%201%2c%20%22total_unwatched%22%3a%20%229%22%2c%20%22discart%22%3a%20%22%22%2c%20%22overlay%22%3a%204%2c%20%22premiered%22%3a%20%222019-10-20%22%2c%20%22clearlogo%22%3a%20%22%22%2c%20%22cast%22%3a%20%5b%7b%22role%22%3a%20%22Angela%20Abar%22%2c%20%22name%22%3a%20%22Regina%20King%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqLPsh6SLw0DSi526g8abEqGJbo3.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Adrian%20Veidt%20%2f%20Ozymandias%22%2c%20%22name%22%3a%20%22Jeremy%20Irons%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f9AWphjIgGX7JjTrwrx3tsTZlUgv.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Judd%20Crawford%22%2c%20%22name%22%3a%20%22Don%20Johnson%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fyQHW10SE2HyuaZmHvUrSxKhqqWg.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Judd%20Crawford%20%2f%20Looking%20Glass%22%2c%20%22name%22%3a%20%22Tim%20Blake%20Nelson%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fdcfdSmVmklb1HXHbB9kySdrl9Nq.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Old%20Man%22%2c%20%22name%22%3a%20%22Louis%20Gossett%20Jr.%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fjZcdOvP9nmLiF7ReKnw4DQbIEid.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Red%20Scare%22%2c%20%22name%22%3a%20%22Andrew%20Howard%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqXEWZDXQRX7UsGlJzKO9dLoCLhq.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Cal%20Abar%22%2c%20%22name%22%3a%20%22Yahya%20Abdul-Mateen%20II%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2flhKObAfoVDU6as0FCgm6y2AAeCO.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Pirate%20Jenny%22%2c%20%22name%22%3a%20%22Adelaide%20Clemens%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fmgOHGacftimR5qBXVzaQoMyVoTX.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Manson%20%2f%20Marionette%22%2c%20%22name%22%3a%20%22Sara%20Vickers%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f4p4OAdzxZ7jyo2lwMEoXu6Fk1zx.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Panda%22%2c%20%22name%22%3a%20%22Jacob%20Ming-Trent%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fxTupOoBtrmhlQQa1vNoS3Di8xT5.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Marcos%20Maez%22%2c%20%22name%22%3a%20%22Tom%20Mison%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2faBDtRCCGgE3Zug2krAhL2IfyvWO.jpg%22%7d%2c%20%7b%22role%22%3a%20%22Topher%20Abar%22%2c%20%22name%22%3a%20%22Dylan%20Schombing%22%2c%20%22thumbnail%22%3a%20%22http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqDSj1htHETBVvof5Jfg4FRMNnyb.jpg%22%7d%5d%2c%20%22tagline%22%3a%20%22%22%2c%20%22tvdb_summary%22%3a%20%7b%22dvdSeasons%22%3a%20%5b%221%22%5d%2c%20%22dvdEpisodes%22%3a%20%229%22%2c%20%22airedEpisodes%22%3a%20%229%22%2c%20%22airedSeasons%22%3a%20%5b%221%22%5d%7d%2c%20%22playcount%22%3a%200%2c%20%22trailer%22%3a%20%22plugin%3a%2f%2fplugin.video.youtube%2fplay%2f%3fvideo_id%3dzymgtV99Rko%22%7d&mode=build_season_list&tmdb_id=79788) failed

**Comment by Tinuz97** [comment]
(movie section works fine,forgot that)

**Comment by Tikipeter** [comment]
There was an update (v.1.5.64b) uploaded an hour ago to fix this. Hopefully if you refresh the tikipeter repo it will push through.....

**Comment by Tinuz97** [comment]
Github has B, repo after several refreshing still shows A for me, I download from git in a minute, but just wanted report it still shows A for me in the repo (refreshed repo several times, and a force update on all repos)

**Comment by Tinuz97** [comment]
Installed B manually (zip from github), working fine now :1st_place_medal:

**Comment by Tikipeter** [comment]
I'm not sure Kodi's refresh for repos is working effectively. I had this problem yesterday. I had to wait a long time for an update to show.

**Comment by Tikipeter** [comment]
While you're here @Tinuz97 , I'm working on your request for supporting languages at the moment. I'm having good success with TMDb (movies). TVDb (TV Shows) looks like it will be more difficult, but hopefully doable.

Do you know any add-ons that currently support this (different languages for metadata specifically, not just a different language for the menus etc within the add-on)? If so I could have a look at the code for any tips/pitfalls...

**Comment by Tinuz97** [comment]
Scrubs V2.
Mostly Dutch language (api on Dutch), but if Dutch is not available, it (I think) auto switching to English for that particular show.

**Comment by Tinuz97** [comment]
Tempest same as Scrubs V2 (mostly Dutch, switching also to English for a particular show if it can't find Dutch language)

**Comment by Tinuz97** [comment]
If it does not switch (forgot which addon), then it shows nothing (so no fallback to English), fallback would be great like scrubs V2 and tempest.

**Comment by Tikipeter** [comment]
Ah OK. Thank you. :)

**Comment by Tinuz97** [comment]
![Screenshot_20191104-175439](https://user-images.githubusercontent.com/47715606/68140510-38e9c880-ff2c-11e9-9005-770c820f590b.jpg)
Tempest, Dutch (api) info

**Comment by Tinuz97** [comment]
![Screenshot_20191104-175446](https://user-images.githubusercontent.com/47715606/68140557-4ef78900-ff2c-11e9-8fd4-0e3b4b0964ea.jpg)
Tempest also, if it can't find Dutch, it has a fallback to English.

**Comment by Tinuz97** [comment]
Wrong screenshot the latest, but it has a fallback to English😅
