### ISSUE TITLE
Errors since last update - v3.0.20

### ISSUE THREAD

**Issue by hindsight2021** [Tikipeter/repository.tikipeter#67]
All of my widgets have failed to load, and I cannot see any trakt tracked objects like “next episodes” or “recently watched” etc.

error:

2022-11-04 08:06:06.522 T:9720    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.DatabaseError'>
                                                   Error Contents: database disk image is malformed
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 3, in <module>
                                                       routing()
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/router.py", line 98, build_single_episode('episode.progress')
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/indexers/episodes.py", line 239, in build_single_episode
                                                       if list_type == 'episode.progress': data = get_in_progress_episodes()
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/watched_status.py", line 190, in get_in_progress_episodes
                                                       dbcur.execute('''SELECT media_id, season, episode, resume_point, last_played, title FROM progress WHERE db_type=?''', ('episode',))
                                                   sqlite3.DatabaseError: database disk image is malformed
                                                   -->End of Python script error report<--
                                                   
2022-11-04 08:06:07.863 T:9720     INFO <general>: Python interpreter stopped

Log is attached.

uninstalled/reinstalled fen release, no change.

deauthed/reauthorized in trakt - error continues.

Log attached.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/9937671/kodi.log)

**Comment by hindsight2021** [comment]
My mistake, issue is with mySQL database

**Comment by hindsight2021** [comment]
Update - I did some preliminary digging and deleted: traktcache4.db in addon_data - as it seemed to revolve around syncing with trakt, specifically around episode data, it's been successfully regenerating without a sqlite error so far.

**Comment by hindsight2021** [comment]
Deauthing from Trakt
Deleting traktcache4.db  
Re-Authing to Trakt
Letting traktcache4.db  rebuild was the solution to this error


Unsure if this was the addon or something on my end, either way - now resolved, above for info only.

Thanks!
