### ISSUE TITLE
Fen error

### ISSUE THREAD

**Issue by extremeaudio** [Tikipeter/repository.tikipeter#7]
When trying to play something from tmdb helper, get a fen error.

```
2022-08-03 13:36:22.752 T:21544   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'title'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 3, in <module>
                                                       routing()
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/router.py", line 55, in routing
                                                       Sources().playback_prep(params)
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 96, in playback_prep
                                                       self._search_info()
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 352, in _search_info
                                                       title = self.get_search_title()
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 366, in get_search_title
                                                       if self.language == 'en': search_title = self.meta['title']
                                                   KeyError: 'title'
                                                   -->End of Python script error report<--
                                                   
2022-08-03 13:36:24.489 T:21544    INFO <general>: Python interpreter stopped
```

**Comment by xyzfre** [comment]
Please read the README.md,, the first sentence of that is,,,,,, TMDbHelper and/or library playback issues are not supported. Fen does not support TMDbHelper.
