### ISSUE TITLE
Fen Errors out

### ISSUE THREAD

**Issue by MrC001** [Tikipeter/repository.tikipeter#703]
Fen does not open at all if you change the menu's in movies or tv. Just receive fen error.  This is in latest update 2.6.01.  Thanx for all you do ..by far best addon out there.

**Comment by trowieuk** [comment]
Error Type: <class 'KeyError'>
                                                   Error Contents: 'media_type'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\trowi\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module>
                                                       routing(argv[2])
                                                     File "C:\Users\trowi\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 60, in routing
                                                       Sources().playback_prep(params)
                                                     File "C:\Users\trowi\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 47, in playback_prep
                                                       self.media_type = self.params['media_type']
                                                   KeyError: 'media_type'

**Comment by Tikipeter** [comment]
@MrC001  working Ok here. I'll need a log for this one.

@trowieuk what is this please? It looks unrelated to this Issue.

**Comment by MrC001** [comment]
I went back to 2.5.xx  -- I will install latest ... on 2.6.01 it happened both on update and fresh install.. I will grab the log ..

**Comment by MrC001** [comment]
Ok so just updated to 2.6.02 -- then rebooted kodi -- tried to run Fen with zero changes and Fen Error..so not related to menu change -- happens once reboot.

2022-03-08 17:09:06.321 T:23047    INFO <general>: Python interpreter stopped
2022-03-08 17:09:06.343 T:23051   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: unable to open database file
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 4, in <module>
                                                       routing(argv[2])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/modules/router.py", line 9, in routing
                                                       from indexers.navigator import Navigator
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/indexers/navigator.py", line 5, in <module>
                                                       from caches.navigator_cache import navigator_cache
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/caches/navigator_cache.py", line 91, in <module>
                                                       navigator_cache = NavigatorCache()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/caches/navigator_cache.py", line 19, in __init__
                                                       self._connect_database()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/caches/navigator_cache.py", line 84, in _connect_database
                                                       self.dbcon = database.connect(dbfile, timeout=timeout, isolation_level=None)
                                                   sqlite3.OperationalError: unable to open database file
                                                   -->End of Python script error report<--

**Comment by MrC001** [comment]
if it helps, when reboot the cache folder in Addon data gets erased.

**Comment by Tikipeter** [comment]
>if it helps, when reboot the cache folder in Addon data gets erased.

Well that is not good. I have absolutely no idea why that would happen.

I've updated Fen probably 50 times since that code was changed.

Does the `caches` folder get remade? Are there valid databases in there afterward if so i.e. they are larger than 0kb?

**Comment by MrC001** [comment]
Rebooted and left it sit for awhile -- just settings file, no cache folder

**Comment by MrC001** [comment]
Does same with fresh install  -- going to wipe kodi to fresh (no other addons etc) and test.

**Comment by Tikipeter** [comment]
That error is not even close to the same issue.

I would guess you are using Fen as a player through TMDbHelper, yes?

**Comment by Tikipeter** [comment]
You need to delete the whole fen userdata folder, then restart Kodi without doing anything else in the meantime.

**Comment by trowieuk** [comment]
> That error is not even close to the same issue.
> 
> I would guess you are using Fen as a player through TMDbHelper, yes?
Oh sorry, thought as it pointed to plugin.video.fen it was a fen issue. All other players work they just ain't as good as fen 👍 
I'll try without tmdbhelper shortly see if I get the same error as MrC001 or if it works.

**Comment by MrC001** [comment]
Ok on fresh install .. problem not there ... No not using it as player with TMDB Helper.  Fresh as in kodi fresh install and fen only addon.  On one with error had bello as default skin -- next will go back to that one and change skin to default kodi skin. Im not running many addons....

**Comment by MrC001** [comment]
Solved -- If you have a builds wizard (I use Open Wizard for backup purposes and to keep things clean) If so, turn of the Clean cache part -- that is wiping the folder.

**Comment by Tikipeter** [comment]
> > That error is not even close to the same issue.
> > I would guess you are using Fen as a player through TMDbHelper, yes?
> 
> Oh sorry, thought as it pointed to plugin.video.fen it was a fen issue. All other players work they just ain't as good as fen 👍 I'll try without tmdbhelper shortly see if I get the same error as MrC001 or if it works.

Unfortunately the Fen TMDbHelper player will need to be updated to work with this version of Fen.

**Comment by Tikipeter** [comment]
Dam. I'll have to change the name of that folder. Second time this has happened because of openWizard. What sort of addon goes around arbitrarily deleting folders because they're named a certain way. Sounds dangerous to me. I'd uninstall that garbage off your system if I were you.

**Comment by MrC001** [comment]
Lol ..... Easy enough to disable the clean.  Also use it to keep dads box
up to date, he's 76 and lives a couple hours away. ... That and syncthing
lets me do it all for him from here...I was able to change his settings
file for the wizard crap to disable the cache clean part.

**Comment by Tikipeter** [comment]
I'll push an update soon with the fix.
