### ISSUE TITLE
Error in Kodi 19.4

### ISSUE THREAD

**Issue by baltzis** [Tikipeter/repository.tikipeter#711]
In Kodi 19.4 (Win10 and Android TV box) I am getting the following error
2022-03-09 15:23:55.353 T:5740 ERROR : EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'media_type'
Traceback (most recent call last):
File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\fen.py", line 4, in routing(argv[2])
File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\router.py", line 60, in routing Sources().playback_prep(params)
File "D:\Kodi\portable_data\addons\plugin.video.fen\resources\lib\modules\sources.py", line 48, in playback_prep self.media_type = self.params['media_type']
KeyError: 'media_type'
-->End of Python script error report<--

**Comment by Tikipeter** [comment]
Look in the Closed Issues here for the new TMDbHelper Fen players posted by a user.

**Comment by baltzis** [comment]
Thanks for your prompt response. I don't seem to be able to find this particular issue. Is there some number for it or a link?

**Comment by Tikipeter** [comment]
https://github.com/Tikipeter/repository.tikipeter/issues/704#issuecomment-1062495488

**Comment by baltzis** [comment]
Thanks!
