### ISSUE TITLE
Real-Debrid cloud/history not working.

### ISSUE THREAD

**Issue by rexiscodin** [Tikipeter/repository.tikipeter#722]
When going to services --> debrid --> cloud, it keeps loading. When clicking on history it says error, check the log for more information. 
Windows 10, Kodi 19.4 Fen 2.6.07

```
2022-03-14 18:57:54.017 T:9224     INFO <general>: CPythonInvoker(2, C:\Users\rex\AppData\Roaming\Kodi\addons\script.module.myaccounts\lib\service.py): script successfully run
2022-03-14 18:57:54.031 T:9632     INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2022-03-14 18:57:54.080 T:360      INFO <general>: initializing python engine.
2022-03-14 18:57:54.083 T:9224     INFO <general>: Python interpreter stopped
2022-03-14 18:57:54.136 T:360      INFO <general>: CPythonInvoker(5, C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py): script successfully run
2022-03-14 18:57:56.076 T:7712     INFO <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2022-03-14 18:57:56.610 T:360      INFO <general>: initializing python engine.
2022-03-14 18:57:56.719 T:360      INFO <general>: CPythonInvoker(5, C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py): script successfully run
2022-03-14 18:57:56.724 T:7504     INFO <general>: ###FEN###: TraktMonitor Service Update FEN TraktMonitor - Success. No Changes Needed - Next Update in 30 minutes...
2022-03-14 18:57:57.263 T:360      INFO <general>: initializing python engine.
2022-03-14 18:57:57.265 T:360      INFO <general>: CPythonInvoker(5, C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py): script successfully run
2022-03-14 18:57:57.826 T:6508     INFO <general>: CPythonInvoker(4, C:\Users\rex\AppData\Roaming\Kodi\addons\service.xbmc.versioncheck\resources\lib\runner.py): script successfully run
2022-03-14 18:57:57.874 T:6508     INFO <general>: Python interpreter stopped
2022-03-14 18:57:57.961 T:360      INFO <general>: initializing python engine.
2022-03-14 18:57:59.092 T:360      INFO <general>: CPythonInvoker(5, C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py): script successfully run
2022-03-14 18:58:01.969 T:4908  WARNING <general>: [WS-Discovery]: The initial search for servers has failed. No servers found.
2022-03-14 18:58:37.850 T:360      INFO <general>: Python interpreter interrupted by user
2022-03-14 18:58:37.850 T:2252    ERROR <general>: Skipped 3 duplicate messages..
2022-03-14 18:58:37.850 T:2252    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?iconImage=C%3a%5cUsers%5crex%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.tikiart%5cresources%5cmedia%5crealdebrid.png&list_name=Real%20Debrid%20Cloud%20Storage&mode=real_debrid.rd_torrent_cloud
2022-03-14 18:58:37.852 T:9632    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?iconImage=C%3a%5cUsers%5crex%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.tikiart%5cresources%5cmedia%5crealdebrid.png&list_name=Real%20Debrid%20Cloud%20Storage&mode=real_debrid.rd_torrent_cloud) failed
2022-03-14 18:58:37.859 T:7032     INFO <general>: initializing python engine.
2022-03-14 18:58:37.914 T:7032     INFO <general>: CPythonInvoker(6, C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py): script successfully run
2022-03-14 18:58:38.497 T:7032     INFO <general>: initializing python engine.
2022-03-14 18:58:40.308 T:7032    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not iterable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 4, in <module>
                                                       routing(argv[2])
                                                     File "C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 210, in routing
                                                       rd_downloads()
                                                     File "C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\real_debrid.py", line 88, in rd_downloads
                                                       my_downloads = [i for i in my_downloads if i['download'].lower().endswith(tuple(extensions))]
                                                   TypeError: 'NoneType' object is not iterable
                                                   -->End of Python script error report<--
                                                   
2022-03-14 18:58:40.381 T:7032     INFO <general>: Python interpreter stopped
2022-03-14 18:58:40.398 T:8776    ERROR <general>: Skipped 1 duplicate messages..
2022-03-14 18:58:40.398 T:8776    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?iconImage=C%3a%5cUsers%5crex%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.tikiart%5cresources%5cmedia%5crealdebrid.png&list_name=Real%20Debrid%20History&mode=real_debrid.rd_downloads
2022-03-14 18:58:40.418 T:9632    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?iconImage=C%3a%5cUsers%5crex%5cAppData%5cRoaming%5cKodi%5caddons%5cscript.tikiart%5cresources%5cmedia%5crealdebrid.png&list_name=Real%20Debrid%20History&mode=real_debrid.rd_downloads) failed
2022-03-14 18:58:40.424 T:6064     INFO <general>: initializing python engine.
2022-03-14 18:58:40.497 T:6064     INFO <general>: CPythonInvoker(7, C:\Users\rex\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py): script successfully run
```
Pretty sure this is what should be needed from the log, if not please let me know.

**Comment by Tikipeter** [comment]
Fixed for next update. :)

**Comment by rexiscodin** [comment]
another thing i discovered was, when trying to add an uncached torrent to RD-Cloud, the same issue happens.
