### ISSUE TITLE
Unable to pass details to FEN player

### ISSUE THREAD

**Issue by JesusonaHarley** [Tikipeter/repository.tikipeter#728]
Hi. Ever since the last update, I’ve been unable to play any item by selecting it from TMDbHelper or Wako. I simply get an error. I’m able to play the same content by looking for it within FEN. Just can’t seem to pass the details to FEN through any other way. This used to work like a breeze before the update. Please find the attached log

2022-03-19 08:09:39.728 T:2660    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'title'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/fen.py", line 4, in <module>
                                                       routing(argv[2])
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/router.py", line 60, in routing
                                                       Sources().playback_prep(params)
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 81, in playback_prep
                                                       self._search_info()
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 317, in _search_info
                                                       title = self._get_search_title(self.meta)
                                                     File "/storage/.kodi/addons/plugin.video.fen/resources/lib/modules/sources.py", line 329, in _get_search_title
                                                       if self.language == 'en': search_title = meta['title']
                                                   KeyError: 'title'
                                                   -->End of Python script error report<--

**Comment by tundrablasen** [comment]
Tmdb Players have been updated? The latest upddd are the fixed this kind of issue

**Comment by JesusonaHarley** [comment]
So, apparently changing the configuration of TMDbH player for fen fixed it for TMDbH. But the issue persists with wako. Keeps giving me the same error of ‘title’

**Comment by Tikipeter** [comment]
I don't think I can do anything about Wako.
I'd need to know what params it sends to Fen to even advise you on what to do.

**Comment by mddfe** [comment]
I believe Wako uses a plugin called nomos to use kodi addons. The most recent version can be found here: https://pastebin.com/raw/8jehXnqz

The relevant part is the following:
```
  "plugin.video.fen": {
    "name": "Fen",
    "plugin": "plugin.video.fen",
    "tvUrl": "/?mode=play_media&vid_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}&plot={info[plot]}",
    "movieUrl": "/?mode=play_media&vid_type=movie&query={name}&year={year}&poster={info[poster]}&plot={info[plot]}&title={title}&tmdb_id={id}"
  }
```

**Comment by JesusonaHarley** [comment]
Yes. That’s the one ^

**Comment by Tikipeter** [comment]
There's your problem. You need to get the Wako dev to replace `vid_type` with `media_type` in both `tvUrl` and `movieUrl`.

**Comment by Tikipeter** [comment]
@mddfe Sorry, I forgot to thank you for posting that.

**Comment by JesusonaHarley** [comment]
Thank you. That helped
